' Gambas module file

'' objeto con la collecion de credenciales del usuario de turno
Property userdata As Collection
Private usuariodat As Collection


Public Sub Main()
 'ojo esto hay que revisar esto 
  Dim instfinicial As FInicial
  Dim instlogin As FormPrincLogin
  
  instlogin = New FormPrincLogin
  instlogin.Show
  If Not IsNull(userdata) Then
    instlogin.Close
    instfinicial = New FInicial 'debera ser asi: New FInicial(userdata_Read()) y asi recibe los datos del usuario por defecto
    instfinicial.Show
    Else
        Print "x"
  Endif

End


'' obtener las credenciales si hubo sesion desde el main module
Private Function userdata_Read() As Collection
    If Not IsNull(usuariodat) Then
        If Val(usuariodat["resultado"]) = 1 Then
            Return usuariodat
        Endif
    Endif
    Return Null
End

'' configurar un usuario desde objetos instanciados en main module
Private Sub userdata_Write(datos As Collection)
    usuariodat = datos
End
