
INSERT INTO `entidad` VALUES('100', 'MCTP', 'VE-ORI', 'Mct Patio Almacen Margarita', 'INACTIVO', 'ADMINISTRATIVO', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '');
INSERT INTO `entidad` VALUES('1001', 'TG2', 'VE-ORI', 'El Tigre - Construccion', 'ESPECIAL', 'ADMINISTRATIVO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `entidad` VALUES('1002', 'GUA', 'VE-CAP', 'Guarenas - Construccion', 'ESPECIAL', 'ADMINISTRATIVO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `entidad` VALUES('1006', 'MULT', 'VE-CAP', 'Multinvest Visa', 'ESPECIAL', 'ADMINISTRATIVO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `entidad` VALUES('1007', 'OFLIDO', 'VE-CAP', 'Oficina Central LIDO', 'ESPECIAL', 'ADMINISTRATIVO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `entidad` VALUES('1008', 'EDR', 'VE-CAP', 'Edificio Don Rafael', 'ESPECIAL', 'ADMINISTRATIVO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `entidad` VALUES('1009', 'CPF', 'INTL', 'Cuentas F Personal C.P.F.', 'ESPECIAL', 'ADMINISTRATIVO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `entidad` VALUES('101', 'EXT', 'VE-CAP', 'Exterior Extrajeros', 'ESPECIAL', 'ADMINISTRATIVO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '20161020094530998.delgado_jesus');
INSERT INTO `entidad` VALUES('1010', 'FIN', 'VE-COC', 'Fincas Barquisimeto', 'ESPECIAL', 'ADMINISTRATIVO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `entidad` VALUES('1016', 'OFDORAL', 'VE-CAP', 'Oficina Legal DORAL', 'ESPECIAL', 'ADMINISTRATIVO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `entidad` VALUES('1017', 'CAB', 'VE-COC', 'Cabudare', 'ESPECIAL', 'ADMINISTRATIVO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '20161021112008998.delgado_jesus');
INSERT INTO `entidad` VALUES('105', 'MCTV', 'VE-CAP', 'Mct Vigilancia Almacen Margarita', '', 'ADMINISTRATIVO', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '');
INSERT INTO `entidad` VALUES('106', 'YUN', 'VE-CAP', 'Yunta - C.c. Yumbo', 'INACTIVO', 'ADMINISTRATIVO', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '');
INSERT INTO `entidad` VALUES('107', 'MMEC', 'VE-ORI', 'Mantenimiento Mecanico', '', 'ADMINISTRATIVO', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '');
INSERT INTO `entidad` VALUES('110', 'MCTA', 'VE-ORI', 'Mct Administrativo Almacen Margarita', '', 'ADMINISTRATIVO', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '');
INSERT INTO `entidad` VALUES('111', 'PRE', 'VE-CAP', 'Presidencia', 'ACTIVO', 'ADMINISTRATIVO', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '');
INSERT INTO `entidad` VALUES('112', 'ADU', 'VE-CAP', 'Aduanas', '', 'ADMINISTRATIVO', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '');
INSERT INTO `entidad` VALUES('113', 'ALC', 'VE-CAP', 'Alcaldias y/o Municipalidad', 'ACTIVO', 'ADMINISTRATIVO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '20161017125139998.admin_user');
INSERT INTO `entidad` VALUES('114', 'DFL', 'VE-CAP', 'Deberes Formales Laborales', '', 'ADMINISTRATIVO', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '');
INSERT INTO `entidad` VALUES('121', 'AUDB', 'VE-CAP', 'Control Cajas Bancos', '', 'ADMINISTRATIVO', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '');
INSERT INTO `entidad` VALUES('122', 'TESB', 'VE-CAP', 'Tesoreria y Bancos', 'ACTIVO', 'ADMINISTRATIVO', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '');
INSERT INTO `entidad` VALUES('131', 'COON', 'VE-CAP', 'Coordinación de Nómina', '', 'ADMINISTRATIVO', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '');
INSERT INTO `entidad` VALUES('132', 'COOB', 'VE-CAP', 'Coordinación de Bienestar Social', '', 'ADMINISTRATIVO', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '');
INSERT INTO `entidad` VALUES('133', 'COOM', 'VE-CAP', 'Coordinación de Muebles', '', 'ADMINISTRATIVO', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '');
INSERT INTO `entidad` VALUES('134', 'COOP', 'VE-CAP', 'Coordinación Personal Tiendas', '', 'ADMINISTRATIVO', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '');
INSERT INTO `entidad` VALUES('135', 'COOC', 'VE-CAP', 'Coordinación de Captación y Desarrollo', '', 'ADMINISTRATIVO', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '');
INSERT INTO `entidad` VALUES('136', 'RRHH', 'VE-CAP', 'Recursos Humanos RRHH', 'ACTIVO', 'ADMINISTRATIVO', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '');
INSERT INTO `entidad` VALUES('137', 'COOA', 'VE-CAP', 'Apoyo Técnico', '', 'ADMINISTRATIVO', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '');
INSERT INTO `entidad` VALUES('138', 'MMES', 'VE-CAP', 'La Estancia Mantenimiento', 'ACTIVO', 'ADMINISTRATIVO', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '');
INSERT INTO `entidad` VALUES('139', 'SALQ', 'VE-CAP', 'Servicios de Alquileres', 'ACTIVO', 'ADMINISTRATIVO', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '');
INSERT INTO `entidad` VALUES('142', 'INV', 'VE-CAP', 'Inventario Departamento', '', 'ADMINISTRATIVO', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '');
INSERT INTO `entidad` VALUES('143', 'CIC', 'VE-CAP', 'Ciclicos', '', 'ADMINISTRATIVO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '20161028155606998.lenz_gerardo');
INSERT INTO `entidad` VALUES('144', 'LEG', 'VE-CAP', 'Legal Abogadas', '', 'ADMINISTRATIVO', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '');
INSERT INTO `entidad` VALUES('150', 'REC', 'VE-CAP', 'Recepcion', '', 'ADMINISTRATIVO', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '');
INSERT INTO `entidad` VALUES('151', 'VIG', 'VE-CAP', 'Seguridad Vigilancia', '', 'ADMINISTRATIVO', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '');
INSERT INTO `entidad` VALUES('152', 'TRA', 'VE-CAP', 'Tramites Externos', '', 'ADMINISTRATIVO', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '');
INSERT INTO `entidad` VALUES('153', 'SEG', 'VE-CAP', 'Seguridad Externa', '', 'ADMINISTRATIVO', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '');
INSERT INTO `entidad` VALUES('154', 'ORG', 'VE-CAP', 'Organizadores', '', 'ADMINISTRATIVO', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '');
INSERT INTO `entidad` VALUES('155', 'ORG', 'VE-CAP', 'Organizadores de Muebles', '', 'ADMINISTRATIVO', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '');
INSERT INTO `entidad` VALUES('156', 'APO', 'VE-CAP', 'Apoyo Tiendas', '', 'ADMINISTRATIVO', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '');
INSERT INTO `entidad` VALUES('157', 'CHO', 'VE-CAP', 'Transporte Choferes', '', 'ADMINISTRATIVO', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '');
INSERT INTO `entidad` VALUES('161', 'SOP', 'VE-CAP', 'Soporte Tecnico Computacion', '', 'ADMINISTRATIVO', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '');
INSERT INTO `entidad` VALUES('162', 'INF', 'VE-CAP', 'Infraestructura y Sistemas', '', 'ADMINISTRATIVO', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '');
INSERT INTO `entidad` VALUES('163', 'CON', 'VE-CAP', 'Contabilidad', '', 'ADMINISTRATIVO', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '');
INSERT INTO `entidad` VALUES('171', 'GES', 'VE-CAP', 'Gestion Financiera', '', 'ADMINISTRATIVO', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '');
INSERT INTO `entidad` VALUES('172', 'COR', 'VE-CAP', 'Correspondencia', '', 'ADMINISTRATIVO', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '');
INSERT INTO `entidad` VALUES('173', 'SER', 'VE-CAP', 'Servicios de Todo', 'ACTIVO', 'ADMINISTRATIVO', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '');
INSERT INTO `entidad` VALUES('174', 'SER', 'VE-CAP', 'Servicios Generales', 'INACTIVO', 'ADMINISTRATIVO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '20161018170156998.delgado_jesus');
INSERT INTO `entidad` VALUES('175', 'CAJ', 'VE-CAP', 'Caja Chica Tiendas', '', 'ADMINISTRATIVO', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '');
INSERT INTO `entidad` VALUES('176', 'TRA', 'VE-CAP', 'Trafico Internacional / Nacional', '', 'ADMINISTRATIVO', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '');
INSERT INTO `entidad` VALUES('181', 'VV', 'VE-CAP', 'La Vista Venevision', '', 'ADMINISTRATIVO', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '');
INSERT INTO `entidad` VALUES('195', 'ANA', 'VE-CAP', 'Analisis de Mercancia', '', 'ADMINISTRATIVO', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '');
INSERT INTO `entidad` VALUES('196', 'DEP', 'VE-CAP', 'Almacen Deposito Sabal', 'ACTIVO', 'ADMINISTRATIVO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '20161028153640998.lenz_gerardo');
INSERT INTO `entidad` VALUES('197', 'DVN', 'VE-CEN', 'Almacen Galpon Valencia Nuevo', '', 'ADMINISTRATIVO', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '');
INSERT INTO `entidad` VALUES('198', 'GAL', 'VE-CAP', 'Almacen y Despacho Galpon Ruices', '', 'ADMINISTRATIVO', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '');
INSERT INTO `entidad` VALUES('199', 'GAL', 'VE-CEN', 'Almacen y Despacho Galpon Rem', 'INACTIVO', 'ADMINISTRATIVO', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '');
INSERT INTO `entidad` VALUES('200', 'VAL', 'VE-CEN', 'Almacen y Despacho Galpon Valencia IX 9', '', 'ADMINISTRATIVO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '20161025131252998.lenz_gerardo');
INSERT INTO `entidad` VALUES('201', 'VAL', 'VE-CEN', 'Almacen y Despacho Galpon Valencia XII 12', '', 'ADMINISTRATIVO', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '');
INSERT INTO `entidad` VALUES('202', 'SHO', 'VE-CAP', 'Showroom Viejo', 'INACTIVO', 'ADMINISTRATIVO', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '');
INSERT INTO `entidad` VALUES('203', 'SHO', 'VE-CAP', 'Showroom Hogar y Ropa', 'ACTIVO', 'ADMINISTRATIVO', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '');
INSERT INTO `entidad` VALUES('204', 'GAS', 'VE-CAP', 'Gastos', 'INACTIVO', 'ADMINISTRATIVO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '20161023142353998.lenz_gerardo');
INSERT INTO `entidad` VALUES('205', 'SUP', 'VE-CAP', 'Supervisión', '', 'ADMINISTRATIVO', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '');
INSERT INTO `entidad` VALUES('206', 'AUD', 'VE-CAP', 'Auditorias', '', 'ADMINISTRATIVO', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '');
INSERT INTO `entidad` VALUES('207', 'DEC', 'VE-CAP', 'Decoración', '', 'ADMINISTRATIVO', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '');
INSERT INTO `entidad` VALUES('208', 'VIS', 'VE-CAP', 'Visual', '', 'ADMINISTRATIVO', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '');
INSERT INTO `entidad` VALUES('209', 'AUD', 'VE-ORI', 'Barquisimeto Auditoria', '', 'ADMINISTRATIVO', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '');
INSERT INTO `entidad` VALUES('210', 'ADM', 'VE-COC', 'Barquisimeto Administración', '', 'ADMINISTRATIVO', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '');
INSERT INTO `entidad` VALUES('211', 'DEP', 'VE-COC', 'Almacen Deposito Zona Barq', '', 'ADMINISTRATIVO', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '');
INSERT INTO `entidad` VALUES('212', 'NÓM', 'VE-CAP', 'Nómina', '', 'ADMINISTRATIVO', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '');
INSERT INTO `entidad` VALUES('213', 'EGR', 'VE-CAP', 'Egresos - Gastos - Prestamos', '', 'ADMINISTRATIVO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '20161018154732213.delgado_jesus');
INSERT INTO `entidad` VALUES('215', 'DEC', 'VE-COC', 'Barquisimeto Decoradores', '', 'ADMINISTRATIVO', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '');
INSERT INTO `entidad` VALUES('220', 'GER', 'VE-COC', 'Gerencia Comercial', '', 'ADMINISTRATIVO', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '');
INSERT INTO `entidad` VALUES('225', 'SEG', 'VE-COC', 'Barquisimeto Seguridad', '', 'ADMINISTRATIVO', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '');
INSERT INTO `entidad` VALUES('230', 'TAL', 'VE-COC', 'Cocina Taller Costura', '', 'ADMINISTRATIVO', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '');
INSERT INTO `entidad` VALUES('235', 'TIE', 'VE-COC', 'Barquisimeto Tiendas', '', 'ADMINISTRATIVO', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '');
INSERT INTO `entidad` VALUES('240', 'VIS', 'VE-COC', 'Barquisimeto Visual', '', 'ADMINISTRATIVO', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '');
INSERT INTO `entidad` VALUES('245', 'OPE', 'VE-CAP', 'Operaciones y Estrategia', '', 'ADMINISTRATIVO', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '');
INSERT INTO `entidad` VALUES('250', 'OSB', 'VE-CAP', 'Oficina Sabal', 'ACTIVO', 'ADMINISTRATIVO', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '');
INSERT INTO `entidad` VALUES('251', 'OES', 'VE-CAP', 'Oficina Estancia', 'INACTIVO', 'ADMINISTRATIVO', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '');
INSERT INTO `entidad` VALUES('252', 'ORC', 'VE-CAP', 'Oficina Ruices', 'ACTIVO', 'ADMINISTRATIVO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '20161020143032998.lenz_gerardo');
INSERT INTO `entidad` VALUES('253', 'OCO', 'VE-COC', 'Oficina Comercial Barquisimeto', 'ACTIVO', 'ADMINISTRATIVO', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '');
INSERT INTO `entidad` VALUES('301', 'PUB', 'VE-CAP', 'Publicidad', 'INACTIVO', 'ADMINISTRATIVO', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '');
INSERT INTO `entidad` VALUES('305', 'RUT', 'VE-CAP', 'Rutas del Caribe', 'ACTIVO', 'ADMINISTRATIVO', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '');
INSERT INTO `entidad` VALUES('310', 'MCT', 'VE-ORI', 'MCT Margarita Container', 'ACTIVO', 'ADMINISTRATIVO', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '');
INSERT INTO `entidad` VALUES('400', 'BLT', 'VE-CAP', 'Boleita Grande', 'ACTIVO', 'SUCURSAL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '20161018164636998.lenz_gerardo');
INSERT INTO `entidad` VALUES('401', 'STB', 'VE-CAP', 'Boleita Sitio', 'ACTIVO', 'SUCURSAL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '20161018164240998.ortega_yamile');
INSERT INTO `entidad` VALUES('405', 'SBC', 'VE-CAP', 'Caracas Sambil Chacao', 'ACTIVO', 'SUCURSAL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '20161017141419998.lenz_gerardo');
INSERT INTO `entidad` VALUES('410', 'CC1', 'VE-CAP', 'Caracas I', 'ACTIVO', 'SUCURSAL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '20161017141430998.lenz_gerardo');
INSERT INTO `entidad` VALUES('415', 'CC2', 'VE-CAP', 'Caracas II', 'ACTIVO', 'SUCURSAL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '20161017141440998.lenz_gerardo');
INSERT INTO `entidad` VALUES('420', 'CC4', 'VE-CAP', 'Caracas IV', 'ACTIVO', 'SUCURSAL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '20161017141450998.lenz_gerardo');
INSERT INTO `entidad` VALUES('425', 'CHA', 'VE-CAP', 'Chacaito', 'ACTIVO', 'SUCURSAL', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '');
INSERT INTO `entidad` VALUES('430', 'CON', 'VE-CAP', 'Concresa', 'ACTIVO', 'SUCURSAL', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '');
INSERT INTO `entidad` VALUES('435', 'PA1', 'VE-CAP', 'El Paraiso I', 'ACTIVO', 'SUCURSAL', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '');
INSERT INTO `entidad` VALUES('440', 'PA2', 'VE-CAP', 'El Paraiso II (C. C. Multiplaza)', 'ACTIVO', 'SUCURSAL', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '');
INSERT INTO `entidad` VALUES('445', 'MRC', 'VE-CAP', 'Las Mercedes', 'ACTIVO', 'SUCURSAL', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '');
INSERT INTO `entidad` VALUES('450', 'LIM', 'VE-CAP', 'Lido Muebles', 'ACTIVO', 'SUCURSAL', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '');
INSERT INTO `entidad` VALUES('455', 'LIR', 'VE-CAP', 'Lido Ropa', 'CERRADA', 'SUCURSAL', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '');
INSERT INTO `entidad` VALUES('460', 'NA1', 'VE-CAP', 'Los Naranjos', 'ACTIVO', 'SUCURSAL', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '');
INSERT INTO `entidad` VALUES('465', 'NA2', 'VE-CAP', 'Los Naranjos II', 'ACTIVO', 'SUCURSAL', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '');
INSERT INTO `entidad` VALUES('470', 'CAS', 'VE-CAP', 'Cascada Los Teques', 'ACTIVO', 'SUCURSAL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '20161017141520998.lenz_gerardo');
INSERT INTO `entidad` VALUES('475', 'SBG', 'VE-CAP', 'Sabana Grande', 'CERRADA', 'SUCURSAL', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '');
INSERT INTO `entidad` VALUES('480', 'STT', 'VE-CAP', 'Santa Teresa', 'ACTIVO', 'SUCURSAL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '20161018212259998.lenz_gerardo');
INSERT INTO `entidad` VALUES('500', 'CAL', 'VE-CEN', 'Calabozo', 'ACTIVO', 'SUCURSAL', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '');
INSERT INTO `entidad` VALUES('505', 'GUA', 'VE-CEN', 'Guacara', 'ACTIVO', 'SUCURSAL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '20161017141459998.lenz_gerardo');
INSERT INTO `entidad` VALUES('510', 'MA1', 'VE-CEN', 'Maracay I Centro', 'ACTIVO', 'SUCURSAL', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '');
INSERT INTO `entidad` VALUES('515', 'MA2', 'VE-CEN', 'Maracay II Parque Aragua', 'ACTIVO', 'SUCURSAL', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '');
INSERT INTO `entidad` VALUES('516', 'MA3', 'VE-CEN', 'Maracay III', 'ACTIVO', 'SUCURSAL', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '');
INSERT INTO `entidad` VALUES('517', 'VIC', 'VE-CEN', 'La Victoria', 'ACTIVO', 'SUCURSAL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '20161024181558998.lenz_gerardo');
INSERT INTO `entidad` VALUES('520', 'PCB', 'VE-CEN', 'Puerto Cabello', 'ACTIVO', 'SUCURSAL', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '');
INSERT INTO `entidad` VALUES('525', 'VC1', 'VE-CEN', 'Valencia I Centro', 'ACTIVO', 'SUCURSAL', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '');
INSERT INTO `entidad` VALUES('530', 'VC2', 'VE-CEN', 'Valencia II Av. Bolivar', 'ACTIVO', 'SUCURSAL', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '');
INSERT INTO `entidad` VALUES('535', 'VC3', 'VE-CEN', 'Valencia III Sambil', 'ACTIVO', 'SUCURSAL', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '');
INSERT INTO `entidad` VALUES('540', 'VC4', 'VE-CEN', 'Valencia IV Metropolis', 'ACTIVO', 'SUCURSAL', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '');
INSERT INTO `entidad` VALUES('600', 'COH', 'VE-FZU', 'Ciudad Ojeda (Hogar)', 'ACTIVO', 'SUCURSAL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '20161019155453998.lenz_gerardo');
INSERT INTO `entidad` VALUES('605', 'COR', 'VE-FZU', 'Ciudad Ojeda (Ropa)', 'ACTIVO', 'SUCURSAL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '20161019155433998.lenz_gerardo');
INSERT INTO `entidad` VALUES('610', 'COS', 'VE-FZU', 'Ciudad Ojeda (Súper)', 'INACTIVO', 'SUCURSAL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '20161019155440998.lenz_gerardo');
INSERT INTO `entidad` VALUES('615', 'COT', 'VE-FZU', 'Ciudad Ojeda (Telas)', 'INACTIVO', 'SUCURSAL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '20161019155504998.lenz_gerardo');
INSERT INTO `entidad` VALUES('620', 'COF', 'VE-FZU', 'Coro Falcon', 'ACTIVO', 'SUCURSAL', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '');
INSERT INTO `entidad` VALUES('625', 'MB2', 'VE-FZU', 'Maracaibo II Galerias', 'ACTIVO', 'SUCURSAL', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '');
INSERT INTO `entidad` VALUES('630', 'MB1', 'VE-FZU', 'Maracaibo Centro Sambil', 'ACTIVO', 'SUCURSAL', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '');
INSERT INTO `entidad` VALUES('631', 'MB3', 'VE-FZU', 'Maracaibo III Centro Sambil', 'CERRADA', 'SUCURSAL', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '');
INSERT INTO `entidad` VALUES('635', 'PF1', 'VE-FZU', 'Punto Fijo Centro', 'ACTIVO', 'SUCURSAL', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '');
INSERT INTO `entidad` VALUES('640', 'PF2', 'VE-FZU', 'Punto Fijo Sambil', 'ACTIVO', 'SUCURSAL', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '');
INSERT INTO `entidad` VALUES('700', 'CAR', 'VE-ORI', 'Carupano I (Ropa)', 'ACTIVO', 'SUCURSAL', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '');
INSERT INTO `entidad` VALUES('705', 'BOL', 'VE-ORI', 'Ciudad Bolivar', 'ACTIVO', 'SUCURSAL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '20161019155230998.lenz_gerardo');
INSERT INTO `entidad` VALUES('710', 'TIG ', 'VE-ORI', 'El Tigre', 'ACTIVO', 'SUCURSAL', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '');
INSERT INTO `entidad` VALUES('715', 'MRG', 'VE-ORI', 'Margarita Centro Sambil', 'ACTIVO', 'SUCURSAL', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '');
INSERT INTO `entidad` VALUES('720', 'MT1', 'VE-ORI', 'Maturin I', 'ACTIVO', 'SUCURSAL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '20161020140414998.lenz_gerardo');
INSERT INTO `entidad` VALUES('725', 'MT2', 'VE-ORI', 'Maturin II', 'ACTIVO', 'SUCURSAL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '20161020140438998.lenz_gerardo');
INSERT INTO `entidad` VALUES('730', 'PLC', 'VE-ORI', 'Puerto La Cruz', 'ACTIVO', 'SUCURSAL', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '');
INSERT INTO `entidad` VALUES('735', 'POZ', 'VE-ORI', 'Puerto Ordaz', 'CERRRADA', 'SUCURSAL', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '');
INSERT INTO `entidad` VALUES('740', 'ORI', 'VE-ORI', 'Orinokia', 'ACTIVO', 'SUCURSAL', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '');
INSERT INTO `entidad` VALUES('745', 'SFX', 'VE-ORI', 'San Felix', 'ACTIVO', 'SUCURSAL', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '');
INSERT INTO `entidad` VALUES('800', 'BRN', 'VE-AND', 'Barinas', 'ACTIVO', 'SUCURSAL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '20161017124932998.admin_user');
INSERT INTO `entidad` VALUES('805', 'VI1', 'VE-AND', 'El Vigia I (Mercancia)', 'ACTIVO', 'SUCURSAL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '20161017125112998.admin_user');
INSERT INTO `entidad` VALUES('810', 'VI2', 'VE-AND', 'El Vigia II (Telas)', 'ACTIVO', 'SUCURSAL', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '');
INSERT INTO `entidad` VALUES('815', 'MRD', 'VE-AND', 'Merida', 'ACTIVO', 'SUCURSAL', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '');
INSERT INTO `entidad` VALUES('820', 'SCR', 'VE-AND', 'San Cristobal Sambil', 'ACTIVO', 'SUCURSAL', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '');
INSERT INTO `entidad` VALUES('821', 'SC2', 'VE-AND', 'San Cristobal Centro', 'CERRADA', 'SUCURSAL', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '');
INSERT INTO `entidad` VALUES('825', 'SB1', 'VE-AND', 'Santa Barbara I', 'ACTIVO', 'SUCURSAL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '20161018164058998.ortega_yamile');
INSERT INTO `entidad` VALUES('830', 'SB2', 'VE-AND', 'Santa Barbara II', 'ACTIVO', 'SUCURSAL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '20161028112253998.lenz_gerardo');
INSERT INTO `entidad` VALUES('835', 'TRU', 'VE-AND', 'Trujillo', 'ACTIVO', 'SUCURSAL', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '');
INSERT INTO `entidad` VALUES('845', 'VLR', 'VE-AND', 'Valera', 'ACTIVO', 'SUCURSAL', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '');
INSERT INTO `entidad` VALUES('900', 'ACA', 'VE-COC', 'Acarigua', 'ACTIVO', 'SUCURSAL', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '');
INSERT INTO `entidad` VALUES('905', 'IPM', 'VE-COC', 'Barquisimeto Ipasme', 'ACTIVO', 'SUCURSAL', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '');
INSERT INTO `entidad` VALUES('915', 'ARC', 'VE-COC', 'Barquisimeto Arca', 'ACTIVO', 'SUCURSAL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '20161017125222998.admin_user');
INSERT INTO `entidad` VALUES('920', 'LAD', 'VE-COC', 'Barquisimeto Lady Cristy', 'ACTIVO', 'SUCURSAL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '20161017131450998.admin_user');
INSERT INTO `entidad` VALUES('925', 'QUE', 'VE-COC', 'Barquisimeto Quemaito', 'ACTIVO', 'SUCURSAL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '20161017130438998.admin_user');
INSERT INTO `entidad` VALUES('930', 'SRQ', 'VE-COC', 'Barquisimeto TMT Sitio', 'ACTIVO', 'SUCURSAL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '20161017140935998.admin_user');
INSERT INTO `entidad` VALUES('931', 'BAR', 'VE-COC', 'Barquisimeto Sambil', 'CERRADO', 'SUCURSAL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '20161017141048998.admin_user');
INSERT INTO `entidad` VALUES('932', 'SAN', 'VE-COC', 'Barquisimeto San', 'ACTIVO', 'SUCURSAL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '20161017141058998.admin_user');
INSERT INTO `entidad` VALUES('933', 'TMT', 'VE-COC', 'TMT', 'ACTIVO', 'SUCURSAL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '20161024182230998.lenz_gerardo');
INSERT INTO `entidad` VALUES('935', 'CAR', 'VE-COC', 'Carora', 'ACTIVO', 'SUCURSAL', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '');
INSERT INTO `entidad` VALUES('940', 'QUI', 'VE-COC', 'Quibor', 'ACTIVO', 'SUCURSAL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '20161017141356998.lenz_gerardo');
INSERT INTO `entidad` VALUES('945', 'TOC', 'VE-COC', 'Tocuyo', 'ACTIVO', 'SUCURSAL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '20161026173311998.lenz_gerardo');
INSERT INTO `entidad` VALUES('998', 'ADM', 'VE-ADM', 'administrador del sistema', 'ACTIVO', 'ADMINISTRATIVO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '20161028150325998.lenz_gerardo');
INSERT INTO `entidad` VALUES('999', 'EST', 'VE-CAP', 'Estancia Real (Castellana)', 'INACTIVO', 'ADMINISTRATIVO', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '');

INSERT INTO `entidad_usuario` VALUES('acarigua', '900', '');
INSERT INTO `entidad_usuario` VALUES('admin_user', '998', NULL);
INSERT INTO `entidad_usuario` VALUES('alcaldias', '113', NULL);
INSERT INTO `entidad_usuario` VALUES('araque_nilexy', '204', NULL);
INSERT INTO `entidad_usuario` VALUES('barinas', '800', NULL);
INSERT INTO `entidad_usuario` VALUES('barquisimetoa', '915', NULL);
INSERT INTO `entidad_usuario` VALUES('barquisimetoc', '920', NULL);
INSERT INTO `entidad_usuario` VALUES('barquisimetoi', '905', '');
INSERT INTO `entidad_usuario` VALUES('barquisimetoq', '925', NULL);
INSERT INTO `entidad_usuario` VALUES('barquisimetos', '932', NULL);
INSERT INTO `entidad_usuario` VALUES('barquisimetot', '930', NULL);
INSERT INTO `entidad_usuario` VALUES('boleitas', '401', '');
INSERT INTO `entidad_usuario` VALUES('boleitat', '400', '');
INSERT INTO `entidad_usuario` VALUES('caceres_milanyela', '204', NULL);
INSERT INTO `entidad_usuario` VALUES('calabozo', '500', '');
INSERT INTO `entidad_usuario` VALUES('caracas1', '410', NULL);
INSERT INTO `entidad_usuario` VALUES('caracas2', '415', NULL);
INSERT INTO `entidad_usuario` VALUES('caracas4', '420', NULL);
INSERT INTO `entidad_usuario` VALUES('caracassambil', '405', NULL);
INSERT INTO `entidad_usuario` VALUES('carora', '935', '');
INSERT INTO `entidad_usuario` VALUES('carupano1', '700', '');
INSERT INTO `entidad_usuario` VALUES('cascada', '470', NULL);
INSERT INTO `entidad_usuario` VALUES('chacaito', '425', '');
INSERT INTO `entidad_usuario` VALUES('ciudadbolivar', '705', '');
INSERT INTO `entidad_usuario` VALUES('concresa', '430', '');
INSERT INTO `entidad_usuario` VALUES('coro', '620', '');
INSERT INTO `entidad_usuario` VALUES('cristobal1', '820', 'And-San Cristobal (Centro Sambil)');
INSERT INTO `entidad_usuario` VALUES('delgado_jesus', '998', NULL);
INSERT INTO `entidad_usuario` VALUES('eltigre', '710', 'Ori-El Tigre');
INSERT INTO `entidad_usuario` VALUES('elvigia1', '805', NULL);
INSERT INTO `entidad_usuario` VALUES('elvigia2', '810', '');
INSERT INTO `entidad_usuario` VALUES('galponruices', '252', NULL);
INSERT INTO `entidad_usuario` VALUES('galponsabal', '196', NULL);
INSERT INTO `entidad_usuario` VALUES('galponvalencia9', '200', NULL);
INSERT INTO `entidad_usuario` VALUES('guacara', '505', NULL);
INSERT INTO `entidad_usuario` VALUES('jimenez_liliana', '998', NULL);
INSERT INTO `entidad_usuario` VALUES('lenz_gerardo', '998', NULL);
INSERT INTO `entidad_usuario` VALUES('lidomueble', '450', '');
INSERT INTO `entidad_usuario` VALUES('lidoropa', '455', '');
INSERT INTO `entidad_usuario` VALUES('maracaibo1', '630', '');
INSERT INTO `entidad_usuario` VALUES('maracaibo2', '625', '');
INSERT INTO `entidad_usuario` VALUES('maracaibo3', '631', '');
INSERT INTO `entidad_usuario` VALUES('maracay1', '510', '');
INSERT INTO `entidad_usuario` VALUES('maracay2', '515', '');
INSERT INTO `entidad_usuario` VALUES('maracay3', '516', '');
INSERT INTO `entidad_usuario` VALUES('margarita', '715', '');
INSERT INTO `entidad_usuario` VALUES('maturin1', '720', '');
INSERT INTO `entidad_usuario` VALUES('maturin2', '725', NULL);
INSERT INTO `entidad_usuario` VALUES('mercedes', '445', '');
INSERT INTO `entidad_usuario` VALUES('merida', '815', '');
INSERT INTO `entidad_usuario` VALUES('naranjos1', '460', '');
INSERT INTO `entidad_usuario` VALUES('naranjos2', '465', '');
INSERT INTO `entidad_usuario` VALUES('ojedahogar', '600', NULL);
INSERT INTO `entidad_usuario` VALUES('ojedaropa', '605', NULL);
INSERT INTO `entidad_usuario` VALUES('orinokia', '740', '');
INSERT INTO `entidad_usuario` VALUES('ortega_yamile', '998', NULL);
INSERT INTO `entidad_usuario` VALUES('paraiso1', '435', '');
INSERT INTO `entidad_usuario` VALUES('paraiso2', '440', '');
INSERT INTO `entidad_usuario` VALUES('parra_naida', '998', NULL);
INSERT INTO `entidad_usuario` VALUES('polanco_ingrid', '998', NULL);
INSERT INTO `entidad_usuario` VALUES('puertocabello', '520', '');
INSERT INTO `entidad_usuario` VALUES('puertolacruz', '730', '');
INSERT INTO `entidad_usuario` VALUES('puertoordaz', '735', '');
INSERT INTO `entidad_usuario` VALUES('puntofijo1', '635', '');
INSERT INTO `entidad_usuario` VALUES('puntofijo2', '640', '');
INSERT INTO `entidad_usuario` VALUES('quibor', '940', NULL);
INSERT INTO `entidad_usuario` VALUES('sabanagrande', '475', '');
INSERT INTO `entidad_usuario` VALUES('sanfelix', '745', 'Ori-San Félix');
INSERT INTO `entidad_usuario` VALUES('santabarbara1', '825', NULL);
INSERT INTO `entidad_usuario` VALUES('santabarbara2', '830', NULL);
INSERT INTO `entidad_usuario` VALUES('santateresa', '480', NULL);
INSERT INTO `entidad_usuario` VALUES('tmtsitio', '933', NULL);
INSERT INTO `entidad_usuario` VALUES('tocuyo', '945', NULL);
INSERT INTO `entidad_usuario` VALUES('trujillo', '835', '');
INSERT INTO `entidad_usuario` VALUES('valencia1', '525', NULL);
INSERT INTO `entidad_usuario` VALUES('valencia2', '530', '');
INSERT INTO `entidad_usuario` VALUES('valencia3', '535', '');
INSERT INTO `entidad_usuario` VALUES('valencia4', '540', '');
INSERT INTO `entidad_usuario` VALUES('valencia_angelica', '204', NULL);
INSERT INTO `entidad_usuario` VALUES('valera', '845', '');
INSERT INTO `entidad_usuario` VALUES('victoria', '517', NULL);
