-- TODO las abrebiaturas y zonas estan malas, pendiente acomodar
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('101','101','VE-CCS','Exterior','ACTIVO',NULL,'999','20161016002045998.admin_user');
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('105','105','VE-CCS','Mct-Vigilancia','ACTIVO','','999','');
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('106','106','VE-CCS','Yunta - C.c. Yumbo','ACTIVO','',' ','');
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('111','111','VE-CCS','Presidencia','ACTIVO','',' ','');
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('112','112','VE-CCS','Aduanas','ACTIVO','','999','');
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('113','113','VE-CCS','Impuestos','ACTIVO','',' ','');
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('121','121','VE-CCS','Bancos','ACTIVO','',' ','');
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('122','122','VE-CCS','Tesoreria','ACTIVO','',' ','');
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('131','131','VE-CCS','Coordinación de Nómina','ACTIVO','',' ','');
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('132','132','VE-CCS','Coordinación de Bienestar Social','ACTIVO','',' ','');
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('133','133','VE-CCS','Coordinación y Archivo de Personal','ACTIVO','',' ','');
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('134','134','VE-CCS','Coordinación Personal Tiendas','ACTIVO','','999','');
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('135','135','VE-CCS','Coordinación de Captación y Desarrollo','ACTIVO','',' ','');
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('136','136','VE-CCS','Departamento Auditoria RRHH','ACTIVO','','999','');
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('137','137','VE-CCS','Apoyo Técnico','ACTIVO','','999','');
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('138','138','VE-CCS','Mantenimiento La Estancia','ACTIVO','','999','');
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('142','142','VE-CCS','Inventario','ACTIVO','',' ','');
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('150','150','VE-CCS','Recepción','ACTIVO','','999','');
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('151','151','VE-CCS','Vigilancia','ACTIVO','','999','');
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('152','152','VE-CCS','Tramites Externos','ACTIVO','','999','');
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('153','153','VE-CCS','Seguridad Tiendas','ACTIVO','','999','');
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('154','154','VE-CCS','Organizadores','ACTIVO','','999','');
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('155','155','VE-CCS','Organizadores de Muebles','ACTIVO','','999','');
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('156','156','VE-CCS','Apoyo Tiendas','ACTIVO','','999','');
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('157','157','VE-CCS','Chofer','ACTIVO','','999','');
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('161','161','VE-CCS','Soporte','ACTIVO','',' ','');
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('162','162','VE-CCS','OASYS','ACTIVO','','999','');
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('163','163','VE-CCS','Contabilidad','ACTIVO','NULL','989','NULL');
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('171','171','VE-CCS','Gestion Financiera','ACTIVO','','999','');
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('172','172','VE-CCS','Correspondencia','ACTIVO','',' ','');
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('173','173','VE-CCS','Servicios','ACTIVO','','999','');
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('174','174','VE-CCS','Servicios Generales','ACTIVO','','999','');
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('181','181','VE-CCS','La Vista','ACTIVO','','999','');
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('195','195','VE-CCS','Analisis de Mercancia','ACTIVO','','999','');
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('196','196','VE-CCS','Deposito Sabal','ACTIVO','','36','');
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('197','197','VE-CEN','Val-Galpon Nuevo','ACTIVO','','42','');
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('198','198','VE-CCS','Gal RCS-Almacen y Despacho','ACTIVO','','34','');
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('199','199','VE-CEN','Gal Rem-Almacen y Despacho','ACTIVO','','999','');
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('2','2','2','2','ACTIVO',NULL,NULL,NULL);
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('200','200','VE-CEN','Val IX-Alamacen y Despacho','ACTIVO','','40','');
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('201','201','VE-CEN','Val XII-Alamacen y Despacho','ACTIVO','','45','');
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('202','202','VE-CCS','Showroom Ropa','ACTIVO','','106','');
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('203','203','VE-CCS','Showroom Hogar','ACTIVO','','107','');
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('204','204','VE-CCS','Gastos','ACTIVO','','999','');
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('205','205','VE-CCS','Supervisión','ACTIVO','',' ','');
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('206','206','VE-CCS','Auditoria Castellana','ACTIVO','',' ','');
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('207','207','VE-CCS','Decoración','ACTIVO','','34','');
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('208','208','VE-CCS','Visual','ACTIVO','','98','');
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('209','209','VE-ORI','Auditoria Barquisimeto','ACTIVO','','999','');
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('210','210','VE-COC','Administración Barquisimeto','ACTIVO','','51','');
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('215','215','VE-COC','Decoradores Barquisimeto','ACTIVO','','51','');
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('220','220','VE-COC','Gerencia Comercial','ACTIVO','','51','');
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('225','225','VE-COC','Seguridad Barquisimeto','ACTIVO','','51','');
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('230','230','VE-COC','Taller Costura / Cocina','ACTIVO','','51','');
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('235','235','VE-COC','Tiendas Barquisimeto','ACTIVO','','999','');
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('240','240','VE-COC','Visual Barquisimeto','ACTIVO','','51','');
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('250','250','VE-CCS','OSB- Oficina Sabal','ACTIVO','','101','');
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('251','251','VE-CCS','OES- Oficina Estancia','ACTIVO','','102','');
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('252','252','VE-CCS','ORC- Oficina Ruices','ACTIVO','','98','');
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('253','253','VE-COC','OCO- Oficina Comercial','ACTIVO','',' ','');
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('301','301','VE-CAR','Publicidad','ACTIVO','','999','');
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('305','305','VE-CAR','Rutas del Caribe','ACTIVO','','999','');
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('310','310','VE-ORI','M.C.T.','ACTIVO','','74','');
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('4','4','4','4','ACTIVO',NULL,'4',NULL);
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('400','BLT','VE-CAR','Cap-Boleita','ACTIVO','NULL','27','20161013152509990.admin_user');
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('401','STB','VE-CAR','Cap-Boleita Sitio','ACTIVO','NULL','43','20161013152821990.admin_user');
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('405','SBC','VE-CCS','Cap-Caracas (C. C. Sambil)','ACTIVO','NULL','90','20161013152945990.admin_user');
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('410','CC1','VE-CCS','Cap-Caracas I','ACTIVO','NULL','30','20161013153055990.admin_user');
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('415','CC2','VE-CCS','Cap-Caracas II','ACTIVO','NULL','31','20161013153308990.admin_user');
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('420','CC4','VE-CCS','Cap-Caracas IV','ACTIVO','','32','');
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('425','CHA','VE-CCS','Cap-Chacaito','ACTIVO','NULL','28','20161013153417990.admin_user');
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('430','430','VE-CAR','Cap-Concresa','ACTIVO','','29','');
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('435','PA1','VE-CAR','Cap-El Paraíso I','ACTIVO','NULL','78','20161013153449990.admin_user');
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('440','PA2','VE-CAR','Cap-El Paraíso II (C. C. Multiplaza)','ACTIVO','NULL','91','20161013153524990.admin_user');
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('445','MRC','VE-CAR','Cap-Las Mercedes','ACTIVO','NULL','49','20161013153559990.admin_user');
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('450','LIM','VE-CCS','Cap-Lido Muebles','ACTIVO','NULL','73','20161013153623990.admin_user');
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('455','455','VE-CCS','Cap-Lido Ropa','ACTIVO','','60','');
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('460','NA1','VE-CAR','Cap-Los Naranjos','ACTIVO','NULL','86','20161013154427990.admin_user');
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('465','NA2','VE-CAR','Cap-Los Naranjos II','ACTIVO','NULL','89','20161013154441990.admin_user');
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('470','CAS','VE-CCS','Cap-Los Teques (C. C. La Cascada)','ACTIVO','NULL','68','20161013154906990.admin_user');
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('475','475','VE-CCS','Cap-Sabana Grande','ACTIVO','','50','');
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('480','STT','VE-CCS','Cap-Santa Teresa','ACTIVO','NULL','79','20161013155103990.admin_user');
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('500','500','VE-CEN','Cen-Calabozo','ACTIVO','NULL','55','20161013161853990.admin_user');
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('505','GUA','VE-CEN','Cen-Guacara','ACTIVO','NULL','83','20161013155315990.admin_user');
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('510','MA1','VE-CEN','Cen-Maracay I (Centro)','ACTIVO','NULL','1','20161013155359990.admin_user');
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('515','MA2','VE-CEN','Cen-Maracay II (Parque Aragua)','ACTIVO','NULL','59','20161013155415990.admin_user');
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('516','MA3','VE-CEN','Cen-Maracay III','ACTIVO','NULL','59','20161013155432990.admin_user');
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('517','VIC','VE-CEN','Cen-La Victoria','ACTIVO','NULL','96','20161013155639990.admin_user');
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('520','PCB','VE-CEN','Cen-Puerto Cabello','ACTIVO','','4','');
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('525','VC1','VE-CEN','Cen-Valencia I (Centro)','ACTIVO','','2','');
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('530','VC2','VE-CEN','Cen-Valencia II (Av. Bolívar)','ACTIVO','','48','');
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('535','VC3','VE-CEN','Cen-Valencia III (Centro Sambil)','ACTIVO','','58','');
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('540','VC4','VE-CEN','Cen-Valencia IV (C.C. Metropolis)','ACTIVO','','75','');
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('600','COH','VE-FZU','Fzu-Ciudad Ojeda (Hogar)','ACTIVO','','20','');
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('605','COR','VE-FZU','Fzu-Ciudad Ojeda (Ropa)','ACTIVO','','19','');
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('610','610','VE-FZU','Fzu-Ciudad Ojeda (Súper)','ACTIVO','','21','');
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('615','615','VE-FZU','Fzu-Ciudad Ojeda (Telas)','ACTIVO','','33','');
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('620','COF','VE-FZU','Fzu-Coro','ACTIVO','','37','');
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('625','MB2','VE-FZU','Fzu-Maracaibo (C. C. Galerías)','ACTIVO','','84','');
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('630','MB1','VE-FZU','Fzu-Maracaibo (Centro Sambil)','ACTIVO','','71','');
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('635','PF1','VE-FZU','Fzu-Punto Fijo','ACTIVO','','38','');
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('640','PF2','VE-FZU','Fzu-Punto Fijo (Centro Sambil)','ACTIVO','','53','');
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('700','700','VE-ORI','Ori-Carúpano I (Ropa)','ACTIVO','','46','');
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('705','BOL','VE-ORI','Ori-Ciudad Bolívar','ACTIVO','','52','');
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('710','TIG','VE-ORI','Ori-El Tigre','ACTIVO','','63','');
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('715','MRG','VE-ORI','Ori-Margarita (Centro Sambil)','ACTIVO','','70','');
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('720','MT1','VE-ORI','Ori-Maturín I','ACTIVO','','61','');
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('725','MT2','VE-ORI','Ori-Maturín II','ACTIVO','','85','');
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('730','PLC','VE-ORI','Ori-Puerto La Cruz','ACTIVO','','5','');
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('735','735','VE-ORI','Ori-Puerto Ordaz','ACTIVO','','39','');
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('740','740','VE-ORI','Ori-Puerto Ordaz (C. C. Orinokia)','ACTIVO','','87','');
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('745','SFX','VE-ORI','Ori-San Félix','ACTIVO','','62','');
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('800','BRN','VE-AND','And-Barinas','ACTIVO','','47','');
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('805','805','VE-AND','And-El Vigía I (Mercancia)','ACTIVO','','24','');
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('810','810','VE-AND','And-El Vigía II (Telas)','ACTIVO','','25','');
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('815','MRD','VE-AND','And-Mérida','ACTIVO','','44','');
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('820','820','VE-AND','And-San Cristobal (Centro Sambil)','ACTIVO','','26','');
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('821','821','VE-AND','And-San Cristobal (Centro)','ACTIVO','','8','');
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('825','SB1','VE-AND','And-Santa Bárbara I','ACTIVO','','22','');
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('830','SB2','VE-AND','And-Santa Bárbara II','ACTIVO','','23','');
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('835','TRU','VE-AND','And-Trujillo','ACTIVO','','9','');
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('845','VLR','VE-AND','And-Valera','ACTIVO','','7','');
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('900','ACA','VE-COC','Coc-Acarigua','ACTIVO','','18','');
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('905','905','VE-COC','Coc-Barquisimeto (Ipasme)','ACTIVO','','14','');
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('915','ARC','VE-COC','Coc-Barquisimeto (Arca)','ACTIVO','','13','');
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('920','LAD','VE-COC','Coc-Barquisimeto (Cristy)','ACTIVO',NULL,'12','20161016013940998.admin_user');
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('925','925','VE-COC','Coc-Barquisimeto (Quemaito)','ACTIVO','','11','');
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('930','TMT','VE-COC','Coc-Barquisimeto (TMT)','ACTIVO','','10','');
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('931','931','VE-COC','Coc-Barquisimeto (Sambil)','ACTIVO','','94','');
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('932','932','VE-COC','Coc-Barquisimeto (San)','ACTIVO','','57','');
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('935','CAR','VE-COC','Coc-Carora','ACTIVO','','17','');
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('940','QUI','VE-COC','Coc-Quibor','ACTIVO','','15','');
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('945','TOC','VE-COC','Coc-Tocuyo','ACTIVO','','16','');
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('990','990','VE-CAR','Administracion auditoria','ACTIVO','','990','NULL');
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('998','adm1','CAP','Administracion systema','ACTIVO',NULL,NULL,'20161016013717998.admin_user');
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('999','999','VE-CAR','Estancia Real (Castellana)','ACTIVO','','999','');
INSERT INTO `entidad` (`cod_entidad`,`abr_entidad`,`abr_zona`,`des_entidad`,`status`,`cod_fondo`,`sello`,`sessionflag`) VALUES ('qqq','qqq','qqq','qqq','ACTIVO',NULL,NULL,NULL);
